#*****************************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# test_project_export.tcl: Tcl script for re-creating project 'test'
#
# Generated by Vivado on Mon Apr 20 16:23:48 EET 2026
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (test_project_export.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/axis_uart_tx_bridge.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_outidx_2_bkb.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_w2_ROM_1Pcud.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_outidx_1_dEe.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_w6_ROM_1PeOg.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_outidx_ROM_1PfYi.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_w11_ROM_1P_LUg8j.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_array_ap_fixed_10_5_5_3_0_5u_config11_Pipeline_DataPrepare.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_fifo_w20_d1_S.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_fifo_w40_d1_S.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_flow_control_loop_pipe.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_flow_control_loop_pipe_sequential_init.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mul_10s_7s_15_1_1.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mul_10s_8s_15_1_1.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mux_10_4_10_1_1.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mux_172_8_10_1_1.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mux_2_1_10_1_1.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mux_4_2_10_1_1.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mux_5_3_10_1_1.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_s.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_s.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_regslice_both.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_s.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_s.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5hbi.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9ibs.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/uart_rx.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/uart_rx_axis_bridge.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/uart_tx.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/ecg_wrapper.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/new/axis_ascii_gen.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/new/uart_tx_fanout.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/new/switch_to_pmod.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_w2_ROM_AUcud.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_w6_ROM_AUeOg.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_outidx_ROM_AUfYi.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_w11_ROM_AUTO_1R.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_fifo_w20_d100000_A.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_fifo_w40_d100000_A.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5g8j.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9hbi.v"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_outidx_2_bkb.dat"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_outidx_ROM_1PfYi.dat"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_w6_ROM_AUeOg.dat"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_w11_ROM_AUTO_1R.dat"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_w2_ROM_1Pcud.dat"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_outidx_1_dEe.dat"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_w2_ROM_AUcud.dat"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_w11_ROM_1P_LUg8j.dat"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_outidx_ROM_AUfYi.dat"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_w6_ROM_1PeOg.dat"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/constrs_1/new/cons.xdc"
#    "/home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/utils_1/imports/synth_1/switch_to_pmod.dcp"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/axis_uart_tx_bridge.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_outidx_2_bkb.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_w2_ROM_1Pcud.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_outidx_1_dEe.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_w6_ROM_1PeOg.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_outidx_ROM_1PfYi.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_w11_ROM_1P_LUg8j.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_array_ap_fixed_10_5_5_3_0_5u_config11_Pipeline_DataPrepare.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_fifo_w20_d1_S.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_fifo_w40_d1_S.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_flow_control_loop_pipe.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_flow_control_loop_pipe_sequential_init.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mul_10s_7s_15_1_1.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mul_10s_8s_15_1_1.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mux_10_4_10_1_1.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mux_172_8_10_1_1.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mux_2_1_10_1_1.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mux_4_2_10_1_1.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mux_5_3_10_1_1.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_s.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_s.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_regslice_both.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_s.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_s.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5hbi.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9ibs.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/uart_rx.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/uart_rx_axis_bridge.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/uart_tx.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/ecg_wrapper.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/new/axis_ascii_gen.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/new/uart_tx_fanout.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/new/switch_to_pmod.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_w2_ROM_AUcud.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_w6_ROM_AUeOg.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_outidx_ROM_AUfYi.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_w11_ROM_AUTO_1R.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_fifo_w20_d100000_A.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_fifo_w40_d100000_A.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5g8j.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9hbi.v"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_outidx_2_bkb.dat"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_outidx_ROM_1PfYi.dat"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_w6_ROM_AUeOg.dat"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_w11_ROM_AUTO_1R.dat"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_w2_ROM_1Pcud.dat"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_outidx_1_dEe.dat"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_w2_ROM_AUcud.dat"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_w11_ROM_1P_LUg8j.dat"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_outidx_ROM_AUfYi.dat"]"\
 "[file normalize "$origin_dir/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_w6_ROM_1PeOg.dat"]"\
 "[file normalize "$origin_dir/test/test.srcs/constrs_1/new/cons.xdc"]"\
 "[file normalize "$origin_dir/test/test.srcs/utils_1/imports/synth_1/switch_to_pmod.dcp"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find local file $ifile "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "test"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "test_project_export.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/test"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7z010clg400-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [current_project]
set_property -name "board_part_repo_paths" -value "[file normalize "$origin_dir/../../../../../../.Xilinx/Vivado/2023.1/xhub/board_store/xilinx_board_store"]" -objects $obj
set_property -name "board_part" -value "digilentinc.com:zybo-z7-10:part0:1.2" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_resource_estimation" -value "0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "platform.board_id" -value "zybo-z7-10" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "sim_compile_state" -value "1" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/axis_uart_tx_bridge.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_outidx_2_bkb.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_w2_ROM_1Pcud.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_outidx_1_dEe.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_w6_ROM_1PeOg.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_outidx_ROM_1PfYi.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_w11_ROM_1P_LUg8j.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_array_ap_fixed_10_5_5_3_0_5u_config11_Pipeline_DataPrepare.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_fifo_w20_d1_S.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_fifo_w40_d1_S.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_flow_control_loop_pipe.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_flow_control_loop_pipe_sequential_init.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mul_10s_7s_15_1_1.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mul_10s_8s_15_1_1.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mux_10_4_10_1_1.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mux_172_8_10_1_1.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mux_2_1_10_1_1.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mux_4_2_10_1_1.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mux_5_3_10_1_1.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_s.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_s.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_regslice_both.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_s.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_s.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5hbi.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9ibs.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/uart_rx.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/uart_rx_axis_bridge.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/uart_tx.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/ecg_wrapper.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/new/axis_ascii_gen.v" ]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/new/uart_tx_fanout.v" ]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/new/switch_to_pmod.v" ]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_w2_ROM_AUcud.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_w6_ROM_AUeOg.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_outidx_ROM_AUfYi.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_w11_ROM_AUTO_1R.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_fifo_w20_d100000_A.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_fifo_w40_d100000_A.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5g8j.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9hbi.v"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_outidx_2_bkb.dat"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_outidx_ROM_1PfYi.dat"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_w6_ROM_AUeOg.dat"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_w11_ROM_AUTO_1R.dat"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_w2_ROM_1Pcud.dat"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_outidx_1_dEe.dat"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_w2_ROM_AUcud.dat"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_w11_ROM_1P_LUg8j.dat"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_outidx_ROM_AUfYi.dat"]\
 [file normalize "${origin_dir}/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_w6_ROM_1PeOg.dat"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_outidx_2_bkb.dat"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Data Files" -objects $file_obj

set file "marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_outidx_ROM_1PfYi.dat"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Data Files" -objects $file_obj

set file "marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_w6_ROM_AUeOg.dat"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Data Files" -objects $file_obj

set file "marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_w11_ROM_AUTO_1R.dat"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Data Files" -objects $file_obj

set file "marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_w2_ROM_1Pcud.dat"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Data Files" -objects $file_obj

set file "marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_outidx_1_dEe.dat"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Data Files" -objects $file_obj

set file "marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_w2_ROM_AUcud.dat"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Data Files" -objects $file_obj

set file "marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_w11_ROM_1P_LUg8j.dat"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Data Files" -objects $file_obj

set file "marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_outidx_ROM_AUfYi.dat"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Data Files" -objects $file_obj

set file "marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_w6_ROM_1PeOg.dat"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Data Files" -objects $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "dataflow_viewer_settings" -value "min_width=16" -objects $obj
set_property -name "top" -value "bd_wrapper" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/test/test.srcs/constrs_1/new/cons.xdc"]"
set file_imported [import_files -fileset constrs_1 [list $file]]
set file "new/cons.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_constrs_file" -value "[get_files *new/cons.xdc]" -objects $obj
set_property -name "target_ucf" -value "[get_files *new/cons.xdc]" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "ecg_wrapper" -objects $obj
set_property -name "top_file" -value "$proj_dir/test.srcs/sources_1/imports/marwan/ecg_wrapper.v" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/test/test.srcs/utils_1/imports/synth_1/switch_to_pmod.dcp" ]\
]
set imported_files [import_files -fileset utils_1 $files]

# Set 'utils_1' fileset file properties for remote files
# None

# Set 'utils_1' fileset file properties for local files
set file "synth_1/switch_to_pmod.dcp"
set file_obj [get_files -of_objects [get_filesets utils_1] [list "*$file"]]
set_property -name "netlist_only" -value "0" -objects $file_obj


# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]


# Adding sources referenced in BDs, if not already added
if { [get_files axis_uart_tx_bridge.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/axis_uart_tx_bridge.v
}
if { [get_files tiny_ecg_no_activ.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ.v
}
if { [get_files tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s.v
}
if { [get_files tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_outidx_2_bkb.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_outidx_2_bkb.v
}
if { [get_files tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_w2_ROM_1Pcud.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_1u_array_ap_fixed_10_5_5_3_0_2u_config2_s_w2_ROM_1Pcud.v
}
if { [get_files tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s.v
}
if { [get_files tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_outidx_1_dEe.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_outidx_1_dEe.v
}
if { [get_files tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_w6_ROM_1PeOg.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_s_w6_ROM_1PeOg.v
}
if { [get_files tiny_ecg_no_activ_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_array_ap_fixed_2u_config2_Pipeline_KernelShiftWidth.v
}
if { [get_files tiny_ecg_no_activ_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_conv_1d_cl_array_array_ap_fixed_4u_config6_Pipeline_KernelShiftWidth.v
}
if { [get_files tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s.v
}
if { [get_files tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_outidx_ROM_1PfYi.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_outidx_ROM_1PfYi.v
}
if { [get_files tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_w11_ROM_1P_LUg8j.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_s_w11_ROM_1P_LUg8j.v
}
if { [get_files tiny_ecg_no_activ_dense_array_array_ap_fixed_10_5_5_3_0_5u_config11_Pipeline_DataPrepare.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_dense_array_array_ap_fixed_10_5_5_3_0_5u_config11_Pipeline_DataPrepare.v
}
if { [get_files tiny_ecg_no_activ_fifo_w20_d1_S.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_fifo_w20_d1_S.v
}
if { [get_files tiny_ecg_no_activ_fifo_w40_d1_S.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_fifo_w40_d1_S.v
}
if { [get_files tiny_ecg_no_activ_flow_control_loop_pipe.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_flow_control_loop_pipe.v
}
if { [get_files tiny_ecg_no_activ_flow_control_loop_pipe_sequential_init.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_flow_control_loop_pipe_sequential_init.v
}
if { [get_files tiny_ecg_no_activ_mul_10s_7s_15_1_1.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mul_10s_7s_15_1_1.v
}
if { [get_files tiny_ecg_no_activ_mul_10s_8s_15_1_1.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mul_10s_8s_15_1_1.v
}
if { [get_files tiny_ecg_no_activ_mux_10_4_10_1_1.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mux_10_4_10_1_1.v
}
if { [get_files tiny_ecg_no_activ_mux_172_8_10_1_1.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mux_172_8_10_1_1.v
}
if { [get_files tiny_ecg_no_activ_mux_2_1_10_1_1.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mux_2_1_10_1_1.v
}
if { [get_files tiny_ecg_no_activ_mux_4_2_10_1_1.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mux_4_2_10_1_1.v
}
if { [get_files tiny_ecg_no_activ_mux_5_3_10_1_1.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_mux_5_3_10_1_1.v
}
if { [get_files tiny_ecg_no_activ_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_s.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5_s.v
}
if { [get_files tiny_ecg_no_activ_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_s.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9_s.v
}
if { [get_files tiny_ecg_no_activ_regslice_both.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_regslice_both.v
}
if { [get_files tiny_ecg_no_activ_relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_s.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_s.v
}
if { [get_files tiny_ecg_no_activ_relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_s.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_s.v
}
if { [get_files tiny_ecg_no_activ_start_for_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_conv_1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_4u_config6_U0.v
}
if { [get_files tiny_ecg_no_activ_start_for_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_dense_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_5u_config11_U0.v
}
if { [get_files tiny_ecg_no_activ_start_for_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5hbi.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_pooling1d_cl_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_config5hbi.v
}
if { [get_files tiny_ecg_no_activ_start_for_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9ibs.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_pooling1d_cl_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_config9ibs.v
}
if { [get_files tiny_ecg_no_activ_start_for_relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_relu_array_ap_fixed_2u_array_ap_fixed_10_5_5_3_0_2u_ReLU_config4_U0.v
}
if { [get_files tiny_ecg_no_activ_start_for_relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/tiny_ecg_no_activ_start_for_relu_array_ap_fixed_4u_array_ap_fixed_10_5_5_3_0_4u_ReLU_config8_U0.v
}
if { [get_files uart_rx.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/uart_rx.v
}
if { [get_files uart_rx_axis_bridge.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/uart_rx_axis_bridge.v
}
if { [get_files uart_tx.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/uart_tx.v
}
if { [get_files ecg_wrapper.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/ecg_wrapper.v
}


# Proc to create BD bd
proc cr_bd_bd { parentCell } {
# The design that will be created by this Tcl proc contains the following 
# module references:
# ecg_wrapper



  # CHANGE DESIGN NAME HERE
  set design_name bd

  common::send_gid_msg -ssname BD::TCL -id 2010 -severity "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:ip:clk_wiz:6.0\
  "

   set list_ips_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2011 -severity "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2012 -severity "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  ##################################################################
  # CHECK Modules
  ##################################################################
  set bCheckModules 1
  if { $bCheckModules == 1 } {
     set list_check_mods "\ 
  ecg_wrapper\
  "

   set list_mods_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2020 -severity "INFO" "Checking if the following modules exist in the project's sources: $list_check_mods ."

   foreach mod_vlnv $list_check_mods {
      if { [can_resolve_reference $mod_vlnv] == 0 } {
         lappend list_mods_missing $mod_vlnv
      }
   }

   if { $list_mods_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2021 -severity "ERROR" "The following module(s) are not found in the project: $list_mods_missing" }
      common::send_gid_msg -ssname BD::TCL -id 2022 -severity "INFO" "Please add source files for the missing module(s) above."
      set bCheckIPsPassed 0
   }
}

  if { $bCheckIPsPassed != 1 } {
    common::send_gid_msg -ssname BD::TCL -id 2023 -severity "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports

  # Create ports
  set tx_0 [ create_bd_port -dir O tx_0 ]
  set rx_0 [ create_bd_port -dir I rx_0 ]
  set arst_n_0 [ create_bd_port -dir I arst_n_0 ]
  set sys_clock [ create_bd_port -dir I -type clk -freq_hz 125000000 sys_clock ]
  set_property -dict [ list \
   CONFIG.PHASE {0.0} \
 ] $sys_clock

  # Create instance: clk_wiz, and set properties
  set clk_wiz [ create_bd_cell -type ip -vlnv xilinx.com:ip:clk_wiz:6.0 clk_wiz ]
  set_property -dict [list \
    CONFIG.CLKOUT1_JITTER {270.480} \
    CONFIG.CLKOUT1_PHASE_ERROR {234.843} \
    CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {30} \
    CONFIG.CLK_IN1_BOARD_INTERFACE {sys_clock} \
    CONFIG.MMCM_CLKFBOUT_MULT_F {39.750} \
    CONFIG.MMCM_CLKOUT0_DIVIDE_F {33.125} \
    CONFIG.MMCM_DIVCLK_DIVIDE {5} \
    CONFIG.USE_BOARD_FLOW {true} \
    CONFIG.USE_LOCKED {false} \
    CONFIG.USE_RESET {false} \
  ] $clk_wiz


  # Create instance: ecg_wrapper_0, and set properties
  set block_name ecg_wrapper
  set block_cell_name ecg_wrapper_0
  if { [catch {set ecg_wrapper_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $ecg_wrapper_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create port connections
  connect_bd_net -net arst_n_0_1 [get_bd_ports arst_n_0] [get_bd_pins ecg_wrapper_0/arst_n]
  connect_bd_net -net clk_wiz_clk_out1 [get_bd_pins clk_wiz/clk_out1] [get_bd_pins ecg_wrapper_0/clk]
  connect_bd_net -net ecg_wrapper_0_tx [get_bd_pins ecg_wrapper_0/tx] [get_bd_ports tx_0]
  connect_bd_net -net rx_0_1 [get_bd_ports rx_0] [get_bd_pins ecg_wrapper_0/rx]
  connect_bd_net -net sys_clock_1 [get_bd_ports sys_clock] [get_bd_pins clk_wiz/clk_in1]

  # Create address segments


  # Restore current instance
  current_bd_instance $oldCurInst

  validate_bd_design
  save_bd_design
  close_bd_design $design_name 
}
# End of cr_bd_bd()
cr_bd_bd ""
set_property REGISTERED_WITH_MANAGER "1" [get_files bd.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files bd.bd ] 

if { [get_files axis_ascii_gen.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/new/axis_ascii_gen.v
}
if { [get_files uart_tx_fanout.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/new/uart_tx_fanout.v
}
if { [get_files uart_tx.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/uart_tx.v
}
if { [get_files axis_uart_tx_bridge.v] == "" } {
  import_files -quiet -fileset sources_1 /home/zkp_egy2/Desktop/old_desktop/Tarek/ECG/tape_out/fpga/test/test.srcs/sources_1/imports/marwan/axis_uart_tx_bridge.v
}


# Proc to create BD design_1
proc cr_bd_design_1 { parentCell } {
# The design that will be created by this Tcl proc contains the following 
# module references:
# axis_ascii_gen, uart_tx_fanout, axis_uart_tx_bridge



  # CHANGE DESIGN NAME HERE
  set design_name design_1

  common::send_gid_msg -ssname BD::TCL -id 2010 -severity "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:ip:clk_wiz:6.0\
  xilinx.com:ip:system_ila:1.1\
  "

   set list_ips_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2011 -severity "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2012 -severity "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  ##################################################################
  # CHECK Modules
  ##################################################################
  set bCheckModules 1
  if { $bCheckModules == 1 } {
     set list_check_mods "\ 
  axis_ascii_gen\
  uart_tx_fanout\
  axis_uart_tx_bridge\
  "

   set list_mods_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2020 -severity "INFO" "Checking if the following modules exist in the project's sources: $list_check_mods ."

   foreach mod_vlnv $list_check_mods {
      if { [can_resolve_reference $mod_vlnv] == 0 } {
         lappend list_mods_missing $mod_vlnv
      }
   }

   if { $list_mods_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2021 -severity "ERROR" "The following module(s) are not found in the project: $list_mods_missing" }
      common::send_gid_msg -ssname BD::TCL -id 2022 -severity "INFO" "Please add source files for the missing module(s) above."
      set bCheckIPsPassed 0
   }
}

  if { $bCheckIPsPassed != 1 } {
    common::send_gid_msg -ssname BD::TCL -id 2023 -severity "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports

  # Create ports
  set sys_clock [ create_bd_port -dir I -type clk -freq_hz 125000000 sys_clock ]
  set_property -dict [ list \
   CONFIG.PHASE {0.0} \
 ] $sys_clock
  set arst_n_0 [ create_bd_port -dir I arst_n_0 ]
  set tx_out_3_0 [ create_bd_port -dir O tx_out_3_0 ]
  set tx_out_2_0 [ create_bd_port -dir O tx_out_2_0 ]
  set tx_out_1_0 [ create_bd_port -dir O tx_out_1_0 ]
  set tx_out_0_0 [ create_bd_port -dir O tx_out_0_0 ]

  # Create instance: clk_wiz, and set properties
  set clk_wiz [ create_bd_cell -type ip -vlnv xilinx.com:ip:clk_wiz:6.0 clk_wiz ]
  set_property -dict [list \
    CONFIG.CLKOUT1_JITTER {143.688} \
    CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {50} \
    CONFIG.CLK_IN1_BOARD_INTERFACE {sys_clock} \
    CONFIG.MMCM_CLKOUT0_DIVIDE_F {20.000} \
    CONFIG.USE_BOARD_FLOW {true} \
    CONFIG.USE_LOCKED {false} \
    CONFIG.USE_RESET {false} \
  ] $clk_wiz


  # Create instance: axis_ascii_gen_0, and set properties
  set block_name axis_ascii_gen
  set block_cell_name axis_ascii_gen_0
  if { [catch {set axis_ascii_gen_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $axis_ascii_gen_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: system_ila_0, and set properties
  set system_ila_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:system_ila:1.1 system_ila_0 ]
  set_property -dict [list \
    CONFIG.C_ADV_TRIGGER {true} \
    CONFIG.C_DATA_DEPTH {32768} \
    CONFIG.C_EN_STRG_QUAL {1} \
    CONFIG.C_MON_TYPE {MIX} \
    CONFIG.C_NUM_MONITOR_SLOTS {1} \
    CONFIG.C_NUM_OF_PROBES {1} \
    CONFIG.C_PROBE0_TYPE {0} \
    CONFIG.C_SLOT_0_APC_EN {0} \
    CONFIG.C_SLOT_0_AXI_DATA_SEL {1} \
    CONFIG.C_SLOT_0_AXI_TRIG_SEL {1} \
    CONFIG.C_SLOT_0_INTF_TYPE {xilinx.com:interface:axis_rtl:1.0} \
  ] $system_ila_0


  # Create instance: uart_tx_fanout_0, and set properties
  set block_name uart_tx_fanout
  set block_cell_name uart_tx_fanout_0
  if { [catch {set uart_tx_fanout_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $uart_tx_fanout_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: axis_uart_tx_bridge_0, and set properties
  set block_name axis_uart_tx_bridge
  set block_cell_name axis_uart_tx_bridge_0
  if { [catch {set axis_uart_tx_bridge_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $axis_uart_tx_bridge_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create interface connections
  connect_bd_intf_net -intf_net axis_ascii_gen_0_m [get_bd_intf_pins axis_ascii_gen_0/m] [get_bd_intf_pins axis_uart_tx_bridge_0/s]
connect_bd_intf_net -intf_net [get_bd_intf_nets axis_ascii_gen_0_m] [get_bd_intf_pins axis_ascii_gen_0/m] [get_bd_intf_pins system_ila_0/SLOT_0_AXIS]
  set_property HDL_ATTRIBUTE.DEBUG {true} [get_bd_intf_nets axis_ascii_gen_0_m]

  # Create port connections
  connect_bd_net -net arst_n_0_1 [get_bd_ports arst_n_0] [get_bd_pins axis_ascii_gen_0/arst_n] [get_bd_pins system_ila_0/resetn] [get_bd_pins axis_uart_tx_bridge_0/arst_n]
  connect_bd_net -net axis_uart_tx_bridge_0_tx [get_bd_pins axis_uart_tx_bridge_0/tx] [get_bd_pins uart_tx_fanout_0/tx_in] [get_bd_pins system_ila_0/probe0]
  connect_bd_net -net clk_wiz_clk_out1 [get_bd_pins clk_wiz/clk_out1] [get_bd_pins axis_ascii_gen_0/clk] [get_bd_pins system_ila_0/clk] [get_bd_pins axis_uart_tx_bridge_0/clk]
  connect_bd_net -net sys_clock_1 [get_bd_ports sys_clock] [get_bd_pins clk_wiz/clk_in1]
  connect_bd_net -net uart_tx_fanout_0_tx_out_0 [get_bd_pins uart_tx_fanout_0/tx_out_0] [get_bd_ports tx_out_0_0]
  connect_bd_net -net uart_tx_fanout_0_tx_out_1 [get_bd_pins uart_tx_fanout_0/tx_out_1] [get_bd_ports tx_out_1_0]
  connect_bd_net -net uart_tx_fanout_0_tx_out_2 [get_bd_pins uart_tx_fanout_0/tx_out_2] [get_bd_ports tx_out_2_0]
  connect_bd_net -net uart_tx_fanout_0_tx_out_3 [get_bd_pins uart_tx_fanout_0/tx_out_3] [get_bd_ports tx_out_3_0]

  # Create address segments


  # Restore current instance
  current_bd_instance $oldCurInst

  save_bd_design
common::send_gid_msg -ssname BD::TCL -id 2050 -severity "WARNING" "This Tcl script was generated from a block design that has not been validated. It is possible that design <$design_name> may result in errors during validation."

  close_bd_design $design_name 
}
# End of cr_bd_design_1()
cr_bd_design_1 ""
set_property REGISTERED_WITH_MANAGER "1" [get_files design_1.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files design_1.bd ] 

#call make_wrapper to create wrapper files
if { [get_property IS_LOCKED [ get_files -norecurse bd.bd] ] == 1  } {
  import_files -fileset sources_1 [file normalize "${origin_dir}/test/test.gen/sources_1/bd/bd/hdl/bd_wrapper.v" ]
} else {
  set wrapper_path [make_wrapper -fileset sources_1 -files [ get_files -norecurse bd.bd] -top]
  add_files -norecurse -fileset sources_1 $wrapper_path
}

if { [get_property IS_LOCKED [ get_files -norecurse design_1.bd] ] == 1  } {
  import_files -fileset sources_1 [file normalize "${origin_dir}/test/test.gen/sources_1/bd/design_1/hdl/design_1_wrapper.v" ]
} else {
  set wrapper_path [make_wrapper -fileset sources_1 -files [ get_files -norecurse design_1.bd] -top]
  add_files -norecurse -fileset sources_1 $wrapper_path
}


set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7z010clg400-1 -flow {Vivado Synthesis 2023} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2023" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "incremental_checkpoint" -value "$proj_dir/test.srcs/utils_1/imports/synth_1/switch_to_pmod.dcp" -objects $obj
set_property -name "auto_incremental_checkpoint" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7z010clg400-1 -flow {Vivado Implementation 2023} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2023" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]
catch {
 if { $idrFlowPropertiesConstraints != {} } {
   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
 }
}

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
