#!/usr/bin/env python3
"""
change_fifo_depth.py
====================
Set the depth of all (or specific) HLS STREAM FIFO pragmas in the
firmware .cpp file generated by hls4ml.

Usage
-----
    # Set ALL FIFOs to depth 1:
    python3 change_fifo_depth.py <HLS_DIR> --depth 1

    # Set only specific FIFOs:
    python3 change_fifo_depth.py <HLS_DIR> --depth 8 --fifo layer2_out layer4_out

    # Dry-run (show what would change, no file written):
    python3 change_fifo_depth.py <HLS_DIR> --depth 4 --dry-run

    # Restore a backup previously saved by this script:
    python3 change_fifo_depth.py <HLS_DIR> --restore

Arguments
---------
    HLS_DIR   Path to the hls4ml project directory (contains firmware/)
    --depth   New FIFO depth (positive integer)
    --fifo    One or more FIFO variable names to target (default: all)
    --dry-run Print the changes without writing to disk
    --restore Restore the .bak backup created by the last run
"""

import argparse
import glob
import os
import re
import shutil
import sys


# ------------------------------------------------------------------ #
# Helpers                                                              #
# ------------------------------------------------------------------ #

def find_firmware_cpp(hls_dir):
    """Return the path to the main firmware .cpp file."""
    pattern = os.path.join(hls_dir, "firmware", "*.cpp")
    files = [f for f in glob.glob(pattern)
             if not os.path.basename(f).startswith("nnet_")]
    if not files:
        sys.exit(f"ERROR: no firmware .cpp found in {hls_dir}/firmware/")
    if len(files) > 1:
        # Prefer the file whose name matches the project directory name
        prj = os.path.basename(os.path.abspath(hls_dir))
        preferred = [f for f in files if prj in os.path.basename(f)]
        if preferred:
            files = preferred
    return files[0]


PRAGMA_RE = re.compile(
    r"(#pragma\s+HLS\s+STREAM\s+variable=(\w+)\s+depth=)\d+",
    re.IGNORECASE,
)


def parse_pragmas(text):
    """Return list of (variable_name, current_depth_str) tuples."""
    results = []
    for m in PRAGMA_RE.finditer(text):
        var = m.group(2)
        depth = m.group(0).split("depth=")[1]
        results.append((var, depth))
    return results


def apply_changes(text, new_depth, target_fifos=None):
    """
    Replace depth=N with depth=<new_depth> for matching pragmas.
    Returns (new_text, list_of_change_descriptions).
    """
    changes = []

    def replacer(m):
        var = m.group(2)
        old_depth = m.group(0).split("depth=")[1]
        if target_fifos and var not in target_fifos:
            return m.group(0)  # leave unchanged
        new_pragma = f"{m.group(1)}{new_depth}"
        if old_depth != str(new_depth):
            changes.append(f"  {var}: depth={old_depth} -> depth={new_depth}")
        else:
            changes.append(f"  {var}: depth={old_depth} (unchanged)")
        return new_pragma

    new_text = PRAGMA_RE.sub(replacer, text)
    return new_text, changes


# ------------------------------------------------------------------ #
# Main                                                                 #
# ------------------------------------------------------------------ #

def main():
    parser = argparse.ArgumentParser(
        description="Change FIFO depth pragmas in an hls4ml firmware .cpp file.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("hls_dir", metavar="HLS_DIR",
                        help="Path to the hls4ml project directory")
    parser.add_argument("--depth", type=int, default=None,
                        help="New FIFO depth value (required unless --restore)")
    parser.add_argument("--fifo", nargs="+", metavar="VAR", default=None,
                        help="Specific FIFO variable name(s) to change (default: all)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Show changes without writing to disk")
    parser.add_argument("--restore", action="store_true",
                        help="Restore the .bak backup created by the last run")
    args = parser.parse_args()

    hls_dir = os.path.abspath(args.hls_dir)
    if not os.path.isdir(hls_dir):
        sys.exit(f"ERROR: directory not found: {hls_dir}")

    cpp_path = find_firmware_cpp(hls_dir)
    bak_path = cpp_path + ".bak"

    # ── Restore mode ──────────────────────────────────────────── #
    if args.restore:
        if not os.path.exists(bak_path):
            sys.exit(f"ERROR: no backup found at {bak_path}")
        shutil.copy2(bak_path, cpp_path)
        print(f"Restored: {cpp_path}")
        print(f"From:     {bak_path}")
        return

    # ── Depth required for all other modes ────────────────────── #
    if args.depth is None:
        parser.error("--depth is required (or use --restore)")
    if args.depth < 1:
        parser.error("--depth must be >= 1")

    with open(cpp_path) as f:
        original = f.read()

    current = parse_pragmas(original)
    if not current:
        sys.exit(f"ERROR: no '#pragma HLS STREAM variable=... depth=...' found in {cpp_path}")

    print(f"Firmware : {cpp_path}")
    print(f"New depth: {args.depth}")
    if args.fifo:
        print(f"Target   : {', '.join(args.fifo)}")
    else:
        print(f"Target   : all FIFOs ({len(current)} found)")
    print()

    new_text, changes = apply_changes(original, args.depth, args.fifo)

    print("Changes:")
    for c in changes:
        print(c)

    if original == new_text:
        print("\nNo changes needed.")
        return

    if args.dry_run:
        print("\n[dry-run] No files written.")
        return

    # Save backup then write
    shutil.copy2(cpp_path, bak_path)
    with open(cpp_path, "w") as f:
        f.write(new_text)

    print(f"\nWritten : {cpp_path}")
    print(f"Backup  : {bak_path}")


if __name__ == "__main__":
    main()
